#! /bin/sh

# Regression test that verifies the functionality of the various utilities.
# Usage: regression tdq-release platform rest-server credentials
# Examples:
#  ./regression nightly.max x86_64-slc5-gcc47-opt  http://pcatd137.cern.ch:8080/ -c atlog
#  ./regression nightly.max x86_64-slc5-gcc47-opt  https://pc-atd-elisa.cern.ch/ -o ~/private/ssocookie.txt
source /afs/cern.ch/atlas/project/tdaq/cmt/bin/cmtsetup.sh $1 $2

echo "elisa_insert: healthy message."
elisa_insert   -s $3 $4 $5 -a "Raul" -j "Testing elisa_insert" -y "Trigger" -e "SCT, CSC, Pixel, DAQ" -p "Trigger_Area=Trigger Group" -p "Trigger_Area.Trigger_Group=MinBiass" -p "Trigger_Area.Trigger_Group=Calo" -b "Regression test of utility elisa_insert" -x "closed" -v 4

echo "elisa_insert: healthy message with attachment."
elisa_insert   -s $3 $4 $5 -a "Raul" -j "Testing elisa_insert with attachment" -y "Run Control" -e "Cryo, Other, RPC, DSS" -p "RunControl_MessageType=problem" -b "Regression test of utility elisa_insert with attachment" -x "open" -m /afs/cern.ch/user/r/rmurillo/public/barcelona.jpg -v 4

echo "elisa_insert: should fail  because option 'subject' is not included."
elisa_insert   -s $3 $4 $5 -a "Raul" -y "Run Control" -e "Cryo, Other, RPC, DSS"  -b "Regression test of utility elisa_insert with attachment" -x "open" -m /afs/cern.ch/user/r/rmurillo/public/barcelona.jpg -v 4

echo "elisa_insert: should fail because option 'type' is not included."
elisa_insert   -s $3 $4 $5 -a "Raul" -j "Testing elisa_insert" -e "SCT, CSC, Pixel, DAQ"  -b "Regression test of utility elisa_insert" -x "closed" -v 4

echo "elisa_insert: should fail because option 'systems affected' is not included."
elisa_insert   -s $3 $4 $5 -a "Raul" -j "Testing elisa_insert" -y "Shift Summary" -b "Regression test of utility elisa_insert" -x "closed" -v 4


echo "elisa_reply: healthy message."
elisa_reply   -s $3 $4 $5 -i 133036  -a "Raul"  -e "SCT, CSC, Pixel, DAQ"  -b "Regression test of utility elisa_reply" -x "closed" -v 4

echo "elisa_reply: healthy message with attachment."
elisa_reply   -s $3 $4 $5 -i 133037 -a "Raul" -e "Pixel, CSC"  -b "Regression test of utility elisa_reply with attachment" -x "open" -m /afs/cern.ch/user/r/rmurillo/public/barcelona.jpg -v 4

echo "elisa_insert: should fail  because option 'id' is not included."
elisa_reply   -s $3 $4 $5  -a "Raul"  -e "SCT, CSC, Pixel, DAQ"  -b "Regression test of utility elisa_reply" -x "closed" -v 4


echo "elisa_update: healthy message."
elisa_update   -s $3 $4 $5 -i 133036 -b "Regression test of utility elisa_update" -v 4

echo "elisa_update: healthy message with attachment."
elisa_update   -s $3 $4 $5 -i 133037 -b "Regression test of utility elisa_update with attachment" -m /afs/cern.ch/user/r/rmurillo/public/barcelona.jpg -v 4

echo "elisa_insert: should fail  because option 'id' is not included."
elisa_update   -s $3 $4 $5 -b "Regression test of utility elisa_update" -v 4


echo "elisa_get: retrieve message with ID 133045."
elisa_get   -s $3 $4 $5 -i 133045 -v 4

echo "elisa_get: retrieve message with search criteria."
elisa_get   -s $3 $4 $5  -v 4 -a "Alina Corso Radu" -l 10 -j "Summary" -e "DAQ"


echo "elisa_config: retrieve ELISA configuration."
elisa_config   -s $3 $4 $5 -v 4

echo "elisa_config: retrieve ELISA configuration for type Trigger."
elisa_config   -s $3 $4 $5 -y Trigger -v 4

echo "elisa_config: retrieve ELISA configuration for type Online."
elisa_config   -s $3 $4 $5 -y Online -v 4